package com.alex;

import com.alex.lox.Location;
import com.alex.lox.Scanner;
import com.alex.lox.Token;
import com.alex.lox.TokenType;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.List;

import static com.alex.lox.TokenType.Symbol.*;
import static org.junit.jupiter.api.Assertions.*;

class ScannerTest {
    record Case<T, U>(T in, U expected) { }
    public static final Token EOF_TOK = new Token(Symbol.EOF, new Location(1, 0));

    // TODO: Fix non-single-character tokens scanning line offset calculation
    @ParameterizedTest
    @MethodSource("simpleScanTests")
    void testScanTokens_simpleCases(Case<String, TokenType> tc) {
        var scanner = new Scanner(tc.in);
        var r = scanner.scanTokens();

        System.out.println(r.tokens());

        assertEquals(tc.expected, r.tokens().getFirst().type());
        assertTrue(r.errors().isEmpty());
    }

    @Test
    void scanTokens_unterminatedString_literalError() {
        var scanner = new Scanner("\"unterminated");
        var result = scanner.scanTokens();

        assertEquals(EOF, result.tokens().getFirst().type());
        assertEquals(1, result.errors().size());
    }

    // Tests generated by Copilot :)
    static List<Case<String, TokenType>> simpleScanTests() {
        var l = LEFT_PAREN;
        return List.of(
                // Single-character tokens
                new Case<>("(", LEFT_PAREN),
                new Case<>(")", RIGHT_PAREN),
                new Case<>("{", LEFT_BRACE),
                new Case<>("}", RIGHT_BRACE),
                new Case<>(",", COMMA),
                new Case<>(".", DOT),
                new Case<>("-", MINUS),
                new Case<>("+", PLUS),
                new Case<>(";", SEMICOLON),
                new Case<>("/", SLASH),
                new Case<>("*", STAR),

                // Multi-character tokens
                new Case<>("!", BANG),
                new Case<>("!=", BANG_EQUAL),
                new Case<>("=", EQUAL),
                new Case<>("==", EQUAL_EQUAL),
                new Case<>(">", GREATER),
                new Case<>(">=", GREATER_EQUAL),
                new Case<>("<", LESS),
                new Case<>("<=", LESS_EQUAL),

                // Identifiers
                new Case<>("identifier", new Ident("identifier")),

                // String literals
                new Case<>("\"hello\"", new StrLit("hello")),

                // Number literals
                new Case<>("123", new NumLit(123.0)),
                new Case<>("123.45", new NumLit(123.45)),

                // Keywords
                new Case<>("and", AND),
                new Case<>("class", CLASS),
                new Case<>("else", ELSE),
                new Case<>("false", FALSE),
                new Case<>("fun", FUN),
                new Case<>("for", FOR),
                new Case<>("if", IF),
                new Case<>("nil", NIL),
                new Case<>("or", OR),
                new Case<>("print", PRINT),
                new Case<>("return", RETURN),
                new Case<>("super", SUPER),
                new Case<>("this", THIS),
                new Case<>("true", TRUE),
                new Case<>("var", VAR),
                new Case<>("while", WHILE)
        );
    }

}