package com.alex;

import com.alex.lox.Location;
import com.alex.lox.Scanner;
import com.alex.lox.Token;
import com.alex.lox.TokenType;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.List;

import static com.alex.lox.TokenType.Symbol.*;
import static org.junit.jupiter.api.Assertions.*;

class ScannerTest {
    record Case<T, U>(T in, U expected) { }
    public static final Token EOF_TOK = new Token(Symbol.EOF, new Location(1, 1));

    // TODO: Fix non-single-character tokens scanning line offset calculation
    @ParameterizedTest
    @MethodSource("simpleScanTests")
    void testScanTokens_simpleCases(Case<String, List<Token>> tc) {
        var scanner = new Scanner(tc.in);
        var r = scanner.scanTokens();

        assertIterableEquals(tc.expected, r.tokens());
        assertTrue(r.errors().isEmpty());
    }

    @Test
    void scanTokens_unterminatedString_literalError() {
        var scanner = new Scanner("\"unterminated");
        var result = scanner.scanTokens();

        assertEquals(List.of(EOF_TOK), result.tokens());
        assertEquals(1, result.errors().size());
    }

    // Tests generated by Copilot :)
    static List<Case<String, List<Token>>> simpleScanTests() {
        var l = LEFT_PAREN;
        return List.of(
                // Single-character tokens
                new Case<>("(", singleTok(l)),
                new Case<>(")", singleTok(RIGHT_PAREN)),
                new Case<>("{", singleTok(LEFT_BRACE)),
                new Case<>("}", singleTok(RIGHT_BRACE)),
                new Case<>(",", singleTok(COMMA)),
                new Case<>(".", singleTok(DOT)),
                new Case<>("-", singleTok(MINUS)),
                new Case<>("+", singleTok(PLUS)),
                new Case<>(";", singleTok(SEMICOLON)),
                new Case<>("/", singleTok(SLASH)),
                new Case<>("*", singleTok(STAR)),

                // Multi-character tokens
                new Case<>("!", singleTok(BANG)),
                new Case<>("!=", singleTok(BANG_EQUAL)),
                new Case<>("=", singleTok(EQUAL)),
                new Case<>("==", singleTok(EQUAL_EQUAL)),
                new Case<>(">", singleTok(GREATER)),
                new Case<>(">=", singleTok(GREATER_EQUAL)),
                new Case<>("<", singleTok(LESS)),
                new Case<>("<=", singleTok(LESS_EQUAL)),

                // Identifiers
                new Case<>("identifier", singleTok(new Ident("identifier"))),

                // String literals
                new Case<>("\"hello\"", singleTok(new StrLit("\"hello\""))),

                // Number literals
                new Case<>("123", singleTok(new NumLit(123.0))),
                new Case<>("123.45", singleTok(new NumLit(123.45))),

                // Keywords
                new Case<>("and", singleTok(AND)),
                new Case<>("class", singleTok(CLASS)),
                new Case<>("else", singleTok(ELSE)),
                new Case<>("false", singleTok(FALSE)),
                new Case<>("fun", singleTok(FUN)),
                new Case<>("for", singleTok(FOR)),
                new Case<>("if", singleTok(IF)),
                new Case<>("nil", singleTok(NIL)),
                new Case<>("or", singleTok(OR)),
                new Case<>("print", singleTok(PRINT)),
                new Case<>("return", singleTok(RETURN)),
                new Case<>("super", singleTok(SUPER)),
                new Case<>("this", singleTok(THIS)),
                new Case<>("true", singleTok(TRUE)),
                new Case<>("var", singleTok(VAR)),
                new Case<>("while", singleTok(WHILE))
        );
    }

    /// Single token at start of source
    private static List<Token> singleTok(TokenType s) {
        return List.of(new Token(s, new Location(1, 1)), EOF_TOK);
    }

}